### ISSUE TITLE
date field not saved in filename

### ISSUE THREAD

**Issue by wm-simon** [doublethreedigital/guest-entries#6]
### Description

When you have a date field in your form, it's gonna saved in the .md file as value, like:
`date: 2021-08-20`

But is should saved as prefix in the filename, like:
2021-08-20.slug.md

### Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.4
doublethreedigital/guest-entries 1.0.2

**Comment by duncanmcclean** [comment]
What does your collection's yaml file look like?

**Comment by wm-simon** [comment]
```
title: Veranstaltungen
template: veranstaltungen/show
layout: layout
search_index: default
mount: c7b3ed3b-d419-4b41-92ea-6a548f02b6f1
taxonomies:
  - veranstaltungsart
  - eigenschaften
revisions: false
route: '{mount}/{year}/{month}/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: unlisted
  future: public

```
